resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:272b83740bd5009c160ad225ed0ef7423ae1be64b41924ab65d00224b6a538a9
  name: controller
  newName: quay.io/yaacov/oc-gate-operator
