resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8c2d1211df48c5ae6d7457609dba75e0b5898ebbb57ca9e3b9ee621e19df67dc
  name: controller
  newName: quay.io/yaacov/oc-gate-operator
