resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:816d4308d4019cb15d70335f69e45cca69bbca4d55d8929394c30dc2e62942ff
  name: controller
  newName: quay.io/yaacov/oc-gate-operator
