resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e8602a79830d1d97d2e2e1b51e3d0ef14a58a621f051c6fed223b27c01cc8304
  name: controller
  newName: quay.io/yaacov/oc-gate-operator
