
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ocgate.yaacov.com
  resources:
  - gatetokens
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ocgate.yaacov.com
  resources:
  - gatetokens/finalizers
  verbs:
  - update
- apiGroups:
  - ocgate.yaacov.com
  resources:
  - gatetokens/status
  verbs:
  - get
  - patch
  - update
