apiVersion: ocgate.yaacov.com/v1beta1
kind: GateServer
metadata:
  name: gateserver-sample
  namespace: kube-gateway
spec:
  apiURL: "https://kubernetes.default.svc"
  route: kube-gateway-proxy.apps-crc.testing
  serviceAccountVerbs:
    - "get"
  serviceAccountAPIGroups:
    - "subresources.kubevirt.io"
  serviceAccountResources:
    - "virtualmachineinstances"
  generateSecret: true
  passThrough: false
  image: "quay.io/yaacov/kube-gateway"
  webAppImage: "quay.io/yaacov/kube-gateway-web-app-novnc"
