name: Test virt-gateway

on:
  push: {}
  pull_request: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build virt-gateway
      run: make
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
        start args: --addons=kubevirt
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images